spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/class101
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /class101

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        ddl-auto: create
        format_sql: true
        default_batch_fetch_size: 1000

logging:
  level:
    root: info
    org:
      hibernate:
        sql: debug
        type: trace

---
spring.profiles: dev

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DATABASE_URL:jdbc:mysql://localhost:3306/class101?serverTimezone=Asia/Seoul&autoReconnect=true&characterEncoding=UTF-8&rewriteBatchedStatements=true}
    username: root
    password: toor